# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b3b21bfb15006172c53df49bd8bdbd8b46222862290849496b2a3aad5b92fbf9f6626f6ee5b6b438f573106641c69d91a8898dcb835649ed654ada6d0cd59d1

test:
  secret_key_base: 29dd4edf5434dd1bac031e45d975af3c6678a24e15b8958eeff9db89fc9ddb6b7b4b70f586307ded5489cc0d537557d416cfe22bbf477742e01112bdca99722b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
